#!/bin/bash

# Run from this directory
cd ${0%/*} ||exit 1     

# Create a build directory
mkdir build             

# Go to build directory
cd build                

# Generate a project buildsystem
cmake -S.. -B. \
      -DMY_CACHE_VAR:STRING="I am a variable 7" \
      -G "MinGW Makefiles"

# Build a project
cmake --build .         