#!/bin/bash

# Run from this directory
cd ${0%/*} ||exit 1  

#find . ! -path . -type f -name Allmake -print -exec bash {} \;
find . -mindepth 2 -type f -name Allmake -exec bash -c '$1 &>/dev/null && echo "$1 ===> done!"' none {} \;
