#!/bin/bash

# Run from this directory
cd ${0%/*} ||exit 1     

# Create a build directory
mkdir build             

# Generate a project buildsystem (a modern way)
cmake   -S. -Bbuild \
        -DCMAKE_BUILD_TYPE=Release

# Build a project
cmake --build build --config Release

# Test a project
cd build
ctest -C Release
cd ..


